# Imagen base de Node.js
FROM node:18

# Crear directorio de la app
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto donde corre tu backend (3000)
EXPOSE 3000

# Comando por defecto para iniciar
CMD ["npm", "run", "dev"]